### ISSUE TITLE
Incorrect indentation in .circleci/config.yaml

### ISSUE THREAD

**Issue by tarohi24** [tarohi24/docsim#37]
```
Build-agent version 1.0.16605-61affc08 (2019-09-26T09:39:10+0000)
Configuration errors: 1 error occurred:

* In step 2 definition: Step

  - name: Set PROJECT_ROOT
    run: map[]
    command: set PROJECT_ROOT=~/project

has incorrect indentation, it should be formatted like:

  - step:
      option1: value
      option2: value
```
